name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main # 만약 여러분의 소스 코드 브랜치가 `main`이라면 여기를 수정합니다.
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Configure Git to accept repository directory
        run: git config --global --add safe.directory /github/workspace

      - name: Install Bundler
        run: gem install bundler -v '2.4.21'

      - name: Install dependencies
        run: bundle install
  
      - name: Build Jekyll site
        run: bundle exec jekyll build

      - uses: jeffreytse/jekyll-deploy-action@v0.5.0
        with:
          provider: "github"
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "gh-pages"
          jekyll_src: "./"
          jekyll_cfg: "_config.yml"
          bundler_ver: "2.4.21" # 여기를 수정했습니다.
          jekyll_build_options: "--future" # 미래의 포스트를 빌드하기 위한 옵션
          # 필요한 추가적인 jekyll build 옵션들을 여기에 추가할 수 있습니다.
