name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main # 만약 여러분의 소스 코드 브랜치가 `main`이라면 여기를 수정합니다.
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Specify your required Ruby version here

      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Configure Git to accept repository directory
        run: git config --global --add safe.directory /github/workspace

      - name: Install Bundler
        run: |
          gem install bundler -v '2.4.21' --user-install
          echo "PATH=$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH" >> $GITHUB_ENV
          bundler -v # Add this line to confirm Bundler version

     
      - name: Check Bundler path
        run: which bundle
      

      - name: Set Bundler path
        run: echo "PATH=$HOME/.gem/ruby/3.0.0/bin:$PATH" >> $GITHUB_ENV
      

      - name: Install dependencies
        run: bundle install
  
      - name: Build Jekyll site
        run: bundle exec jekyll build --future
    

      - uses: jeffreytse/jekyll-deploy-action@v0.5.0
        with:
          provider: "github"
          token: ${{ secrets.SECRET }}
          branch: "gh-pages"
          jekyll_src: "./"
          jekyll_cfg: "_config.yml"
          bundler_ver: "2.4.21" # 여기를 수정했습니다.
          jekyll_build_options: "--future" # 미래의 포스트를 빌드하기 위한 옵션
          # 필요한 추가적인 jekyll build 옵션들을 여기에 추가할 수 있습니다.
