jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6  # or another version that you need

    - name: Install Bundler
      run: gem install bundler:2.4.21

    - name: Bundle Install
      run: bundle install

    - name: Build Jekyll Site
      uses: actions/jekyll-build-pages@v1
      with:
        source: './'
        destination: './_site'
        token: ${{ secrets.GITHUB_TOKEN }}
